site_name: Gardening App
nav:
  - Home: index.md
  - System Requirements: system-requirements.md
  - General:
    - Resources: resources.md
    - Author Resume: "https://resume.prosperousheart.com/"
# theme:
#   name: readthedocs
theme:
  name: mkdocs
  locale: en
  user_color_mode_toggle: true
  # analytics:
  #   gtag: G-ABC123
  navigation_depth: 4
markdown_extensions:
  - toc:
      permalink: "#"
      # baselevel: 2
      # separator: "_"
repo_url: https://github.com/ProsperousHeart/gardening-app
# repo_name: 'GH'
# edit_uri: blob/main/docs/
site_description: "Easy app for new gardeners & Community gardeners."
site_author: "Kassandra Keeton, the Prosperous Heart"
copyright: "2025"
exclude_docs: |
  api-config.json    # A file with this name anywhere.
  /requirements.txt  # Top-level "docs/requirements.txt".
  *.py               # Any file with this extension anywhere.
  index_ORIGINAL.md  # backup of original index file
