# Generated by Django 5.0.4 on 2024-04-23 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('aa', 'Academic Article'), ('bl', 'Blog'), ('bk', 'Book'), ('mg', 'Master Gardener'), ('ot', 'Other'), ('yt', 'YouTube')], max_length=2)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plants.plant')),
            ],
        ),
    ]
