# Generated by Django 5.0.4 on 2024-04-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0002_plantlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantlink',
            options={'ordering': ['type', 'title']},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='resources',
        ),
        migrations.AddField(
            model_name='plant',
            name='earth_kind',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='plantlink',
            name='plant',
        ),
        migrations.AddField(
            model_name='plantlink',
            name='plant',
            field=models.ManyToManyField(blank=True, to='Plants.plant'),
        ),
    ]
