# Generated by Django 5.0.4 on 2024-04-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0006_plant_plant_type_alter_plant_germination_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='height',
            new_name='height_min',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='spacing',
            new_name='spacing_min',
        ),
        migrations.AddField(
            model_name='plant',
            name='height_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='spacing_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
