# Generated by Django 5.0.4 on 2024-04-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0013_alter_plantlink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantlink',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
