# Generated by Django 5.0.4 on 2024-04-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0016_nursery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='exposure',
            field=models.CharField(choices=[('fs', 'Full Sun (6+)'), ('fp', 'Full to Partial Sun (4-6H)'), ('pu', 'Partial Sun (morning, 4-6H)'), ('pd', 'Partial Shade (morning, <=4H)'), ('sh', 'Shade')], default='fs', max_length=2),
        ),
    ]
