# Generated by Django 5.0.4 on 2024-04-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0023_plant_good_for_rock_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='deadhead_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
