# Generated by Django 5.0.4 on 2024-04-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0024_plant_deadhead_suggested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='attracts_butterflies',
            new_name='is_butterfly_attractor',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='deadhead_suggested',
            new_name='is_deadhead_suggested',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='drought_tolerant',
            new_name='is_drought_tolerant',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='earth_kind',
            new_name='is_earth_kind',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='good_for_border',
            new_name='is_good_for_border',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='good_for_container',
            new_name='is_good_for_container',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='good_for_landscape',
            new_name='is_good_for_landscape',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='good_for_rock_garden',
            new_name='is_good_for_rock_garden',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='heat_tolerant',
            new_name='is_heat_tolerant',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='pollinator_friendly',
            new_name='is_pollinator_friendly',
        ),
        migrations.AddField(
            model_name='plant',
            name='is_non_gmo',
            field=models.BooleanField(default=False),
        ),
    ]
