# Generated by Django 5.0.4 on 2024-04-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0029_alter_plant_hardiness_zone_high_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursery',
            options={'ordering': ['name']},
        ),
    ]
