# Generated by Django 5.0.4 on 2024-04-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100)),
                ('name_scientific', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hardiness_zone_low', models.PositiveSmallIntegerField()),
                ('hardiness_zone_high', models.PositiveSmallIntegerField()),
                ('spacing', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('suggested_container_size', models.PositiveIntegerField()),
                ('medicinal_benefits', models.TextField()),
                ('companion_plants', models.TextField()),
                ('resources', models.TextField()),
                ('germination_days', models.PositiveSmallIntegerField()),
                ('maturity_days', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('related_plants', models.ManyToManyField(blank=True, to='Plants.plant')),
            ],
        ),
    ]
