# Generated by Django 5.0.4 on 2024-04-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0004_plant_exposure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='companion_plants',
        ),
        migrations.AlterField(
            model_name='plant',
            name='germination_days',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='hardiness_zone_high',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='hardiness_zone_low',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='maturity_days',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='medicinal_benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='spacing',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='suggested_container_size',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
