# Generated by Django 5.0.4 on 2024-04-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0005_remove_plant_companion_plants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('an', 'Annual'), ('bi', 'Biennial'), ('pe', 'Perennial'), ('sh', 'Shrub'), ('tr', 'Tree'), ('vi', 'Vine')], default='pe', max_length=2),
        ),
        migrations.AlterField(
            model_name='plant',
            name='germination_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='hardiness_zone_high',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='hardiness_zone_low',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='maturity_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='spacing',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='suggested_container_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
