# Generated by Django 5.0.4 on 2024-04-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0009_alter_plantlink_plant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
