# Generated by Django 5.0.4 on 2024-04-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0014_alter_plantlink_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='drought_tolerant',
            field=models.BooleanField(default=False),
        ),
    ]
