# Generated by Django 5.0.4 on 2024-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0017_alter_plant_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='heat_tolerant',
            field=models.BooleanField(default=False),
        ),
    ]
