# Generated by Django 5.0.4 on 2024-04-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0020_plant_attracts_butterflies'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='good_for_container',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='good_for_landscape',
            field=models.BooleanField(default=False),
        ),
    ]
