# Generated by Django 5.0.4 on 2024-04-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0021_plant_good_for_container_plant_good_for_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='good_for_border',
            field=models.BooleanField(default=False),
        ),
    ]
