# Generated by Django 5.0.4 on 2024-04-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0025_rename_attracts_butterflies_plant_is_butterfly_attractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
    ]
