# Generated by Django 5.0.4 on 2024-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0031_plant_is_mosquito_repellent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_good_for_shrubs',
            field=models.BooleanField(default=False),
        ),
    ]
